pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('project-03-ci-cd') {
                    sh 'docker build -t rudrateja04/jenkins-cicd-app:latest .'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-password', variable: 'DOCKER_PASS')]) {
                    sh '''
                      echo $DOCKER_PASS | docker login -u rudrateja04 --password-stdin
                      docker push rudrateja04/jenkins-cicd-app:latest
                    '''
                }
            }
        }

        stage('Deploy Application') {
            steps {
                sh '''
                  docker stop cicd-app || true
                  docker rm cicd-app || true
                  docker run -d -p 5000:5000 --name cicd-app rudrateja04/jenkins-cicd-app:latest
                '''
            }
        }
    }
}
